//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace BUSINESS.WsGetPathDecriptHollerith {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebserviceOpenPdfSapSoap", Namespace="http://eepsa.com.br/")]
    public partial class WebserviceOpenPdfSap : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback openPdfOperationCompleted;
        
        private System.Threading.SendOrPostCallback printFileTotemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebserviceOpenPdfSap() {
            this.Url = global::BUSINESS.Properties.Settings.Default.BUSINESS_WsGetPathDecriptHollerith_WebserviceOpenPdfSap;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event openPdfCompletedEventHandler openPdfCompleted;
        
        /// <remarks/>
        public event printFileTotemCompletedEventHandler printFileTotemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eepsa.com.br/openPdf", RequestNamespace="http://eepsa.com.br/", ResponseNamespace="http://eepsa.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string openPdf(string matricula, string path) {
            object[] results = this.Invoke("openPdf", new object[] {
                        matricula,
                        path});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void openPdfAsync(string matricula, string path) {
            this.openPdfAsync(matricula, path, null);
        }
        
        /// <remarks/>
        public void openPdfAsync(string matricula, string path, object userState) {
            if ((this.openPdfOperationCompleted == null)) {
                this.openPdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnopenPdfOperationCompleted);
            }
            this.InvokeAsync("openPdf", new object[] {
                        matricula,
                        path}, this.openPdfOperationCompleted, userState);
        }
        
        private void OnopenPdfOperationCompleted(object arg) {
            if ((this.openPdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.openPdfCompleted(this, new openPdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eepsa.com.br/printFileTotem", RequestNamespace="http://eepsa.com.br/", ResponseNamespace="http://eepsa.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string printFileTotem(string matricula, string path) {
            object[] results = this.Invoke("printFileTotem", new object[] {
                        matricula,
                        path});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void printFileTotemAsync(string matricula, string path) {
            this.printFileTotemAsync(matricula, path, null);
        }
        
        /// <remarks/>
        public void printFileTotemAsync(string matricula, string path, object userState) {
            if ((this.printFileTotemOperationCompleted == null)) {
                this.printFileTotemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprintFileTotemOperationCompleted);
            }
            this.InvokeAsync("printFileTotem", new object[] {
                        matricula,
                        path}, this.printFileTotemOperationCompleted, userState);
        }
        
        private void OnprintFileTotemOperationCompleted(object arg) {
            if ((this.printFileTotemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.printFileTotemCompleted(this, new printFileTotemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void openPdfCompletedEventHandler(object sender, openPdfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class openPdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal openPdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void printFileTotemCompletedEventHandler(object sender, printFileTotemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class printFileTotemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal printFileTotemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591