//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Totem.WsOpenPdf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eepsa.com.br/", ConfigurationName="WsOpenPdf.WebserviceOpenPdfSapSoap")]
    public interface WebserviceOpenPdfSapSoap {
        
        // CODEGEN: Generating message contract since element name matricula from namespace http://eepsa.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eepsa.com.br/openPdf", ReplyAction="*")]
        Totem.WsOpenPdf.openPdfResponse openPdf(Totem.WsOpenPdf.openPdfRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class openPdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="openPdf", Namespace="http://eepsa.com.br/", Order=0)]
        public Totem.WsOpenPdf.openPdfRequestBody Body;
        
        public openPdfRequest() {
        }
        
        public openPdfRequest(Totem.WsOpenPdf.openPdfRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eepsa.com.br/")]
    public partial class openPdfRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string matricula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        public openPdfRequestBody() {
        }
        
        public openPdfRequestBody(string matricula, string path) {
            this.matricula = matricula;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class openPdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="openPdfResponse", Namespace="http://eepsa.com.br/", Order=0)]
        public Totem.WsOpenPdf.openPdfResponseBody Body;
        
        public openPdfResponse() {
        }
        
        public openPdfResponse(Totem.WsOpenPdf.openPdfResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eepsa.com.br/")]
    public partial class openPdfResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string openPdfResult;
        
        public openPdfResponseBody() {
        }
        
        public openPdfResponseBody(string openPdfResult) {
            this.openPdfResult = openPdfResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebserviceOpenPdfSapSoapChannel : Totem.WsOpenPdf.WebserviceOpenPdfSapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebserviceOpenPdfSapSoapClient : System.ServiceModel.ClientBase<Totem.WsOpenPdf.WebserviceOpenPdfSapSoap>, Totem.WsOpenPdf.WebserviceOpenPdfSapSoap {
        
        public WebserviceOpenPdfSapSoapClient() {
        }
        
        public WebserviceOpenPdfSapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebserviceOpenPdfSapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebserviceOpenPdfSapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebserviceOpenPdfSapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Totem.WsOpenPdf.openPdfResponse Totem.WsOpenPdf.WebserviceOpenPdfSapSoap.openPdf(Totem.WsOpenPdf.openPdfRequest request) {
            return base.Channel.openPdf(request);
        }
        
        public string openPdf(string matricula, string path) {
            Totem.WsOpenPdf.openPdfRequest inValue = new Totem.WsOpenPdf.openPdfRequest();
            inValue.Body = new Totem.WsOpenPdf.openPdfRequestBody();
            inValue.Body.matricula = matricula;
            inValue.Body.path = path;
            Totem.WsOpenPdf.openPdfResponse retVal = ((Totem.WsOpenPdf.WebserviceOpenPdfSapSoap)(this)).openPdf(inValue);
            return retVal.Body.openPdfResult;
        }
    }
}
